import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {dirname,join,basename} from 'node:path';
import {fileURLToPath} from 'node:url';
import {finalizeReadoutArtifact,markdownReport,verifyUnchanged} from '../../refit-saved.mjs';
const dir=dirname(fileURLToPath(import.meta.url));
const hash=value=>createHash('sha256').update(value).digest('hex');
const reportBytes=readFileSync(join(dir,'report.json'));
const report=JSON.parse(reportBytes);
assert.equal(report.studyReceipt.sha256,'c408b8d8103be7de2332a5bd1c09ccbc029192e2cc2e62e4b21b4044c3ac9b88');
verifyUnchanged(report.inputHashesBefore);
const previous=report.studyReceipt;
const corrected=join(dirname(previous.path),'RoAlgoV3_refit_saved_v2_24_'+Date.now()+'_readout.json');
const receipt=finalizeReadoutArtifact({sourcePath:previous.path,outputPath:corrected,expectedSha256:previous.sha256});
writeFileSync(join(dir,basename(corrected)),readFileSync(corrected),{flag:'wx'});
writeFileSync(join(dir,'report.before-provenance-finalization.json'),reportBytes,{flag:'wx'});
writeFileSync(join(dir,'report.before-provenance-finalization.md'),readFileSync(join(dir,'report.md')),{flag:'wx'});
report.studyReceipt=receipt;
report.provenanceFinalization={atUTC:new Date().toISOString(),previousStudyReceipt:previous,changes:['Added top-level readoutOnly=true'],refitExecuted:false,newNativeSteps:0,executedSourceHashesUnchanged:true,finalizerSha256:hash(readFileSync(fileURLToPath(import.meta.url))),toolSha256:hash(readFileSync(new URL('../../refit-saved.mjs',import.meta.url)))};
writeFileSync(join(dir,'report.json'),JSON.stringify(report,null,2)+'\n');
writeFileSync(join(dir,'report.md'),markdownReport(report)+'\nThe corrected artifact adds the explicit `readoutOnly=true` flag. The prior artifact is preserved byte-for-byte; no model was refitted. Executed source hashes still identify the original Luau snapshots. The metadata correction is recorded separately in report.json.\n');
assert.equal(hash(readFileSync(previous.path)),previous.sha256);
verifyUnchanged(report.inputHashesBefore);
console.log(JSON.stringify({receipt,previousArtifactUnchanged:true,originalInputsUnchanged:true,refitExecuted:false,readoutOnly:JSON.parse(readFileSync(corrected)).readoutOnly}));
