// Generates lab/generated/ConfigData.luau from lab/config/default.json (the single source of truth).
// Usage: node tools/gen-config.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { toLuau } from "./luau-literal.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

export function generateConfig(jsonText) {
  const config = JSON.parse(jsonText);
  const sha256 = createHash("sha256").update(jsonText, "utf8").digest("hex");
  return (
    "-- GENERATED by tools/gen-config.mjs from lab/config/default.json. Do not edit by hand.\n" +
    `-- source sha256 ${sha256}\n` +
    `return { sourceSha256 = "${sha256}", values = ${toLuau(config)} }\n`
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const text = readFileSync(join(root, "lab/config/default.json"), "utf8");
  const out = join(root, "lab/generated/ConfigData.luau");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, generateConfig(text), "utf8");
  console.log("wrote", out);
}
