// Lab orchestrator (Node 24, built-ins only). Packages, hashes and moves data; all modelling runs in Luau.
//
//   node tools/run-lab.mjs prepare <O14|R50|H14>
//       Runs lab/cli/prepare.luau; saves runs/<EXP>/inputs/<P>.json (every paired observation, transformed
//       with the training-only scaler), runs/<EXP>/<P>-feature-schema.json, <P>-scaler.json,
//       <P>-input-diagnostics.json, and CLI chunk modules runs/<EXP>/luau/inputs_<P>/.
//   node tools/run-lab.mjs streams <jobId> --profiles O14,R50 --from <decisionIso> --to <decisionIso>
//         [--presets P1,P2,P3] [--drives O14=0.3,R50=0.3] [--lanes 4] [--max-pairs N] [--page 400]
//       Writes an aligned job: runs/<EXP>/inputs/<jobId>-<P>.json (local indices) and <jobId>-job.json.
//       Refuses any final-period row unless --final and a model lock exists for every profile.
//   node tools/run-lab.mjs assemble <P> <phase> <jobId>[,<jobId>...]
//       Joins job state pages back to the profile's paired stream by timestamp, checks coverage of every
//       observation of the phase (dev = train+validation, final), writes runs/<EXP>/luau/states_<P>-<phase>/.
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, renameSync, statSync } from "node:fs";
import { toLuau } from "./luau-literal.mjs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runLuau, luauIdentity } from "./luau-run.mjs";
import { canonicalSha256, sha256Hex } from "./canonical-json.mjs";
import { loadStatePages } from "./states-to-luau.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const EXP = "exp-20261005";
const expDir = join(root, "runs", EXP);
const CHUNK = 1000;

function writeJson(file, value) {
  mkdirSync(dirname(file), { recursive: true });
  const text = JSON.stringify(value);
  const tmp = file + ".tmp";
  writeFileSync(tmp, text, "utf8");
  renameSync(tmp, file);
  return sha256Hex(Buffer.from(text, "utf8"));
}

function readJson(file) {
  return JSON.parse(readFileSync(file, "utf8"));
}

function num(x) {
  if (!Number.isFinite(x)) throw new Error(`non-finite ${x}`);
  return Object.is(x, -0) ? "-0" : String(x);
}

const SPLIT_CODE = { train: 1, validation: 2, final: 3, none: 0 };

function writeChunks(dir, rows, toLuau, indexFields) {
  mkdirSync(dir, { recursive: true });
  const chunks = [];
  for (let c = 0; c * CHUNK < rows.length; c++) {
    const name = `Chunk${String(c + 1).padStart(3, "0")}`;
    writeFileSync(join(dir, `${name}.luau`), `return {\n${rows.slice(c * CHUNK, (c + 1) * CHUNK).map(toLuau).join(",\n")}\n}\n`, "utf8");
    chunks.push(name);
  }
  const fields = Object.entries(indexFields).map(([k, v]) => `${k} = ${typeof v === "string" ? JSON.stringify(v) : v}`);
  writeFileSync(
    join(dir, "index.luau"),
    `-- GENERATED by tools/run-lab.mjs. Do not edit.\nreturn { ${fields.join(", ")}, chunks = { ${chunks.map((c) => `"${c}"`).join(", ")} } }\n`,
    "utf8",
  );
}

async function prepare(profile) {
  const started = new Date().toISOString();
  const { result, rows } = await runLuau("lab/cli/prepare.luau", [profile], { cwd: root });
  if (rows.length !== result.pairs) throw new Error(`prepare ${profile}: ${rows.length} rows for ${result.pairs} pairs`);
  rows.forEach((r, k) => {
    if (r.i !== k + 1) throw new Error(`row order broken at ${k + 1}`);
    if (r.x.length !== result.schema.dimension) throw new Error(`row ${r.i} dimension ${r.x.length}`);
  });
  const header = {
    experimentId: EXP,
    profileId: profile,
    dimension: result.schema.dimension,
    count: rows.length,
    counts: result.counts,
    schemaVersion: result.schema.version,
    formulaVersion: result.schema.formulaVersion,
    scalerSha256: canonicalSha256(result.scaler),
    schemaSha256: canonicalSha256(result.schema),
    configSha256: result.configSha256,
    luau: luauIdentity(),
    preparedAt: started,
  };
  header.inputsSha256 = canonicalSha256(rows);
  writeJson(join(expDir, "inputs", `${profile}.json`), { header, rows });
  writeJson(join(expDir, `${profile}-feature-schema.json`), result.schema);
  writeJson(join(expDir, `${profile}-scaler.json`), result.scaler);
  writeJson(join(expDir, `${profile}-input-diagnostics.json`), {
    diagnostics: result.diagnostics,
    observedBySplit: result.observedBySplit,
    datasetStats: result.datasetStats,
    counts: result.counts,
    seconds: result.seconds,
  });
  writeChunks(
    join(expDir, "luau", `inputs_${profile}`),
    rows,
    (r) => `{${[r.i, r.t, r.seg, r.off, SPLIT_CODE[r.split]].map(num).join(",")},{${r.x.map(num).join(",")}}}`,
    { count: rows.length, dimension: header.dimension, sha256: header.inputsSha256, profileId: profile },
  );
  console.log(JSON.stringify({ profile, rows: rows.length, counts: result.counts, inputsSha256: header.inputsSha256, seconds: result.seconds }));
}

function parseOpts(argv) {
  const o = {};
  for (let k = 0; k < argv.length; k++) {
    if (argv[k].startsWith("--")) {
      const key = argv[k].slice(2);
      const next = argv[k + 1];
      if (next === undefined || next.startsWith("--")) o[key] = true;
      else {
        o[key] = next;
        k++;
      }
    }
  }
  return o;
}

function streams(jobId, opts) {
  if (!/^[A-Za-z0-9_-]{1,40}$/.test(jobId)) throw new Error("bad job id");
  const profiles = String(opts.profiles).split(",");
  const presets = String(opts.presets ?? "P1,P2,P3").split(",");
  const drives = {};
  for (const kv of String(opts.drives ?? "").split(",").filter(Boolean)) {
    const [p, v] = kv.split("=");
    drives[p] = Number(v);
  }
  const driveGrid = opts["drive-grid"] ? String(opts["drive-grid"]).split(",").map(Number) : null;
  const from = Date.parse(opts.from) / 1000;
  const to = Date.parse(opts.to) / 1000;
  if (!Number.isFinite(from) || !Number.isFinite(to) || !(from < to)) throw new Error("--from/--to decision-time window required");
  const config = readJson(join(root, "lab/config/default.json"));
  const testStart = config.splits.testStart;
  const isFinal = from >= testStart;
  if (!isFinal && to > testStart) throw new Error("a development job may not reach the final period");
  const locks = {};
  if (isFinal) {
    if (!opts.final) throw new Error("final-period job requires --final");
    // Plan section 4: final physics only after EVERY included profile is locked, and only the locked
    // preset/drive of each profile; nothing about the physical configuration comes from the command line.
    const included = readJson(join(expDir, "protocol.json")).profiles.included;
    for (const p of included) {
      const lockFile = join(root, "runs", `${p}-a1`, "model-lock.json");
      if (!existsSync(lockFile)) throw new Error(`no model lock for ${p}; final physics is sealed until every included profile is locked`);
      locks[p] = readJson(lockFile);
    }
    for (const p of profiles) if (!locks[p]) throw new Error(`profile ${p} is not an included, locked profile`);
    for (const k of ["drives", "presets", "drive-grid", "selected"]) {
      if (opts[k] !== undefined) throw new Error(`--${k} is not allowed for a final job: preset and drive come from each model lock`);
    }
  } else if (!opts["drive-grid"] && existsSync(join(expDir, "calibration.json"))) {
    const chosen = readJson(join(expDir, "calibration.json")).chosen;
    for (const p of profiles) {
      if (Number(String(opts.drives ?? "").split(",").find((kv) => kv.startsWith(p + "="))?.split("=")[1]) !== chosen[p]) {
        throw new Error(`development drive for ${p} must equal the calibrated drive ${chosen[p]}`);
      }
    }
  }
  if (existsSync(join(expDir, `${jobId}-job.json`))) {
    for (const p of profiles) {
      if (existsSync(join(expDir, "state-cache", `${jobId}-${p}`))) throw new Error(`job ${jobId} already has state pages; use a new job id`);
    }
  }
  const data = {};
  for (const p of profiles) data[p] = readJson(join(expDir, "inputs", `${p}.json`));
  // select rows by decision time window, whole segments only, aligned across profiles by timestamp
  const select = (p) => data[p].rows.filter((r) => r.t + 3600 >= from && r.t + 3600 < to);
  const base = select(profiles[0]);
  let selected = base;
  if (opts["max-pairs"]) {
    const max = Number(opts["max-pairs"]);
    let cut = base.length;
    if (max < base.length) {
      cut = max;
      while (cut > 0 && base[cut].off !== 1) cut--;
    }
    selected = base.slice(0, cut);
  }
  if (selected.length === 0) throw new Error("empty window");
  if (selected[0].off !== 1) throw new Error("window must start at a segment start");
  const tset = selected.map((r) => r.t);
  const out = {};
  for (const p of profiles) {
    const rows = select(p).slice(0, selected.length);
    if (rows.length !== selected.length || rows.some((r, k) => r.t !== tset[k] || r.off !== selected[k].off)) {
      throw new Error(`profile ${p} rows are not aligned with ${profiles[0]} in this window`);
    }
    let seg = 0;
    out[p] = rows.map((r, k) => {
      if (r.off === 1) seg++;
      return { i: k + 1, t: r.t, seg, off: r.off, gi: r.i, x: r.x };
    });
  }
  const selectedPreset = {};
  for (const kv of String(opts.selected ?? "").split(",").filter(Boolean)) {
    const [p, v] = kv.split("=");
    selectedPreset[p] = v;
  }
  const reservoirs = [];
  for (const p of profiles) {
    if (isFinal) {
      reservoirs.push({ key: `${p}:${locks[p].preset}`, profileId: p, presetId: locks[p].preset, drive: locks[p].drive });
      continue;
    }
    for (const preset of selectedPreset[p] ? [selectedPreset[p]] : presets) {
      if (driveGrid) {
        for (const d of driveGrid) reservoirs.push({ key: `${p}:${preset}:d${d}`, profileId: p, presetId: preset, drive: d });
      } else {
        if (!Number.isFinite(drives[p])) throw new Error(`--drives must give a drive for ${p}`);
        reservoirs.push({ key: `${p}:${preset}`, profileId: p, presetId: preset, drive: drives[p] });
      }
    }
  }
  const projectionArtifacts = {};
  for (const p of profiles) projectionArtifacts[p] = `projection-D${data[p].header.dimension}.json`;
  const streamProfiles = {};
  const hashes = {};
  for (const p of profiles) {
    const name = `${jobId}-${p}`;
    streamProfiles[name] = p;
    hashes[name] = writeJson(join(expDir, "inputs", `${name}.json`), {
      header: { jobId, profileId: p, count: out[p].length, sourceInputsSha256: data[p].header.inputsSha256, from: opts.from, to: opts.to },
      rows: out[p],
    });
  }
  const job = {
    experimentId: EXP,
    runId: EXP,
    jobId,
    streams: Object.keys(streamProfiles),
    streamProfiles,
    reservoirs,
    projectionArtifacts,
    pageRows: Number(opts.page ?? 400),
    lanes: Number(opts.lanes ?? 4),
    rows: selected.length,
    segments: out[profiles[0]].at(-1).seg,
    window: { from: opts.from, to: opts.to },
    final: isFinal,
    streamHashes: hashes,
  };
  writeJson(join(expDir, `${jobId}-job.json`), job);
  console.log(JSON.stringify({ jobId, rows: job.rows, segments: job.segments, reservoirs: reservoirs.length, lanes: job.lanes }));
}

function assemble(profile, phase, jobIds) {
  if (phase !== "dev" && phase !== "final") throw new Error("phase must be dev or final");
  const data = readJson(join(expDir, "inputs", `${profile}.json`));
  const want = data.rows.filter((r) => (phase === "dev" ? r.split === "train" || r.split === "validation" : r.split === phase));
  // The physical configuration every job must have used for this profile and phase.
  let expectPresets, expectDrive;
  if (phase === "dev") {
    expectPresets = ["P1", "P2", "P3"];
    expectDrive = readJson(join(expDir, "calibration.json")).chosen[profile];
  } else {
    const lockRec = readJson(join(runDir(profile), "model-lock.json"));
    expectPresets = [lockRec.preset];
    expectDrive = lockRec.drive;
  }
  const byT = new Map();
  let keys = null;
  const provenance = [];
  for (const jobId of jobIds) {
    const stream = `${jobId}-${profile}`;
    const job = readJson(join(expDir, `${jobId}-job.json`));
    if (phase === "final" && job.final !== true) throw new Error(`${jobId} is not a final job`);
    if (phase === "dev" && job.final) throw new Error(`${jobId} is a final job`);
    const specs = job.reservoirs.filter((r) => r.profileId === profile);
    if (JSON.stringify(specs.map((s) => s.presetId)) !== JSON.stringify(expectPresets) || specs.some((s) => s.drive !== expectDrive || s.key !== `${profile}:${s.presetId}`)) {
      throw new Error(`${jobId}: reservoirs for ${profile} are ${JSON.stringify(specs)}, expected presets ${expectPresets} at drive ${expectDrive}`);
    }
    const streamFile = join(expDir, "inputs", `${stream}.json`);
    if (sha256Hex(readFileSync(streamFile)) !== job.streamHashes[stream]) throw new Error(`${stream}: input stream file differs from the job definition`);
    const dir = join(expDir, "state-cache", stream);
    const pages = loadStatePages(dir);
    const jobInputs = readJson(streamFile);
    if (jobInputs.header.sourceInputsSha256 !== data.header.inputsSha256) throw new Error(`${stream}: states were driven by inputs ${jobInputs.header.sourceInputsSha256}, current inputs are ${data.header.inputsSha256}`);
    if (pages.rows.length !== jobInputs.rows.length) throw new Error(`${stream}: ${pages.rows.length} state rows for ${jobInputs.rows.length} inputs`);
    pages.rows.forEach((r, k) => {
      const inp = jobInputs.rows[k];
      if (r.t !== inp.t || r.off !== inp.off) throw new Error(`${stream}: state row ${k + 1} does not match its input`);
      if (byT.has(r.t)) throw new Error(`${stream}: duplicate state for t=${r.t}`);
      byT.set(r.t, { gi: inp.gi, s: r.s });
    });
    if (keys === null) keys = pages.keys;
    if (JSON.stringify(keys) !== JSON.stringify(pages.keys)) throw new Error("reservoir keys differ across jobs");
    if (JSON.stringify(keys) !== JSON.stringify(expectPresets.map((p) => `${profile}:${p}`))) throw new Error(`${stream}: state keys ${keys} do not match the expected configuration`);
    provenance.push({ jobId, stream, pageHashes: pages.pageHashes, rows: pages.rows.length, streamSha256: job.streamHashes[stream], drive: expectDrive, presets: expectPresets });
  }
  const missing = want.filter((r) => !byT.has(r.t));
  if (missing.length) throw new Error(`${profile} ${phase}: ${missing.length} observations have no physics state (first t=${missing[0].t})`);
  const wantT = new Set(want.map((r) => r.t));
  const extra = [...byT.keys()].filter((t) => !wantT.has(t));
  if (extra.length) throw new Error(`${profile} ${phase}: ${extra.length} states outside the phase (first t=${extra[0]})`);
  const rows = want.map((r) => ({ i: r.i, t: r.t, s: byT.get(r.t).s }));
  const inputsSha256 = data.header.inputsSha256;
  const sha256 = canonicalSha256({ keys, inputsSha256, drive: expectDrive, rows: rows.map((r) => [r.i, r.t, keys.map((k) => r.s[k])]) });
  writeChunks(
    join(expDir, "luau", `states_${profile}-${phase}`),
    rows,
    (r) => `{${num(r.i)},${num(r.t)},${keys.map((k) => `{${r.s[k].map(num).join(",")}}`).join(",")}}`,
    { count: rows.length, sha256, profileId: profile, phase, inputsSha256 },
  );
  const keysLuau = `return { ${keys.map((k) => JSON.stringify(k)).join(", ")} }\n`;
  writeFileSync(join(expDir, "luau", `states_${profile}-${phase}`, "keys.luau"), keysLuau, "utf8");
  writeJson(join(expDir, `${profile}-${phase}-states-manifest.json`), { profile, phase, keys, rows: rows.length, sha256, inputsSha256, drive: expectDrive, provenance });
  console.log(JSON.stringify({ profile, phase, rows: rows.length, keys, sha256 }));
}

const runDir = (profile) => join(root, "runs", `${profile}-a1`);

function writeJsonl(file, rows) {
  mkdirSync(dirname(file), { recursive: true });
  const text = rows.map((r) => JSON.stringify(r)).join("\n") + "\n";
  const tmp = file + ".tmp";
  writeFileSync(tmp, text, "utf8");
  renameSync(tmp, file);
  return sha256Hex(Buffer.from(text, "utf8"));
}

function refuseExisting(file) {
  if (existsSync(file)) throw new Error(`refusing to overwrite ${file}`);
}

async function fit(profile) {
  const dir = runDir(profile);
  if (existsSync(join(dir, "model-lock.json"))) throw new Error(`${profile} is locked; refitting would change a frozen model`);
  const { result, rows } = await runLuau("lab/cli/fit.luau", [profile], { cwd: root });
  const models = {};
  for (const [name, entry] of Object.entries(result.models)) models[name] = entry;
  const model = {
    runId: `${profile}-a1`,
    profileId: profile,
    preset: result.selected.preset,
    rawLag: Number(String(result.selected.rawRidge.config).slice(1)),
    selected: result.selected,
    trainingTargetMean: result.trainingTargetMean,
    trainingTargetStd: result.trainingTargetStd,
    inputsSha256: result.inputsSha256,
    statesSha256: result.statesSha256,
    stateKeys: result.stateKeys,
    models,
  };
  writeJson(join(dir, "model.json"), model);
  writeJson(join(dir, "markov-model.json"), result.markov);
  writeJson(join(dir, "candidates.json"), { budget: result.budget, candidates: result.candidates, ranked: result.ranked, origins: result.origins });
  writeJson(join(dir, "validation-summary.json"), { summary: result.validationSummary, origins: result.origins, trainingTargetStd: result.trainingTargetStd });
  const vh = writeJsonl(join(dir, "validation-predictions.jsonl"), rows);
  console.log(JSON.stringify({ profile, selected: result.selected, origins: result.origins, budget: result.budget, validationPredictionsSha256: vh, seconds: result.seconds }));
}

function hashTree(dirs) {
  const out = {};
  const walk = (d) => {
    for (const name of readdirSync(join(root, d)).sort()) {
      if (name.startsWith(".")) continue;
      const rel = `${d}/${name}`;
      const full = join(root, rel);
      if (statSync(full).isDirectory()) walk(rel);
      else if (/\.(luau|mjs|json)$/.test(name)) out[rel] = sha256Hex(readFileSync(full));
    }
  };
  for (const d of dirs) walk(d);
  return out;
}

async function lock(profile) {
  const dir = runDir(profile);
  const lockFile = join(dir, "model-lock.json");
  refuseExisting(lockFile);
  const model = readJson(join(dir, "model.json"));
  const markov = readJson(join(dir, "markov-model.json"));
  const protocol = readJson(join(expDir, "protocol.json"));
  const calibration = readJson(join(expDir, "calibration.json"));
  const devStates = readJson(join(expDir, `${profile}-dev-states-manifest.json`));
  const inputsHeader = readJson(join(expDir, "inputs", `${profile}.json`)).header;
  // The lock attests only what the model was actually fitted on.
  if (model.statesSha256 !== devStates.sha256) throw new Error(`${profile}: model was fitted on states ${model.statesSha256}, assembled dev states are ${devStates.sha256}`);
  if (model.inputsSha256 !== inputsHeader.inputsSha256 || model.inputsSha256 !== protocol.inputs.inputsSha256[profile]) throw new Error(`${profile}: model inputs differ from the protocol/current inputs`);
  if (devStates.drive !== calibration.chosen[profile] || devStates.inputsSha256 !== model.inputsSha256) throw new Error(`${profile}: dev states drive/inputs differ from calibration/model`);
  if (!protocol.profiles.included.includes(profile)) throw new Error(`${profile} is not an included profile`);
  const modelSha256 = canonicalSha256(model);
  const markovSha256 = canonicalSha256(markov);
  const code = hashTree(["lab/src", "lab/cli", "lab/config", "tools"]);
  const lockRecord = {
    runId: `${profile}-a1`,
    experimentId: EXP,
    profileId: profile,
    statement: "final metrics not yet evaluated",
    lockedAt: new Date().toISOString(),
    selected: model.selected,
    preset: model.preset,
    drive: calibration.chosen[profile],
    hashes: {
      model: modelSha256,
      markov: markovSha256,
      protocol: protocol.sha256,
      calibration: calibration.sha256,
      inputs: model.inputsSha256,
      devStates: devStates.sha256,
      scaler: canonicalSha256(readJson(join(expDir, `${profile}-scaler.json`))),
      featureSchema: canonicalSha256(readJson(join(expDir, `${profile}-feature-schema.json`))),
      projection: canonicalSha256(readJson(join(expDir, `projection-D${profile === "R50" ? 50 : 14}.json`))),
      config: canonicalSha256(readJson(join(root, "lab/config/default.json"))),
      code: canonicalSha256(code),
    },
    codeFiles: code,
    luau: luauIdentity(),
  };
  // Luau artifact for predict.luau: exactly the saved JSON values.
  const artifact = {
    runId: model.runId,
    profileId: profile,
    preset: model.preset,
    rawLag: model.rawLag,
    trainingTargetMean: model.trainingTargetMean,
    trainingTargetStd: model.trainingTargetStd,
    inputsSha256: model.inputsSha256,
    statesSha256: model.statesSha256,
    modelSha256,
    models: model.models,
    markov,
  };
  mkdirSync(join(dir, "luau"), { recursive: true });
  const luauText = `-- GENERATED from model.json + markov-model.json at lock. Do not edit.\nreturn ${toLuau(artifact)}\n`;
  writeFileSync(join(dir, "luau", "model.luau"), luauText, "utf8");
  lockRecord.hashes.modelLuau = sha256Hex(Buffer.from(luauText, "utf8"));
  // Prove the saved artifact (JSON -> Luau) reproduces the fitted reference predictions BEFORE locking:
  // predict.luau rebuilds the reference rows from the development stream and asserts agreement within 1e-12.
  const check = await runLuau("lab/cli/predict.luau", [profile, "validation"], { cwd: root });
  if (!(check.result.referenceChecks > 0) || check.result.failures !== 0) throw new Error(`${profile}: artifact verification failed ${JSON.stringify(check.result)}`);
  lockRecord.artifactVerification = { referenceChecks: check.result.referenceChecks, validationForecasts: check.result.forecasts, phase: "validation" };
  writeJson(lockFile, lockRecord);
  console.log(JSON.stringify({ profile, lock: lockFile, model: modelSha256, preset: model.preset, referenceChecks: check.result.referenceChecks }));
}

// Recomputes the artifact hashes and compares them with the lock (before predict and evaluate use them).
function verifyLock(profile) {
  const dir = runDir(profile);
  const lockRec = readJson(join(dir, "model-lock.json"));
  if (canonicalSha256(readJson(join(dir, "model.json"))) !== lockRec.hashes.model) throw new Error(`${profile}: model.json differs from the lock`);
  if (canonicalSha256(readJson(join(dir, "markov-model.json"))) !== lockRec.hashes.markov) throw new Error(`${profile}: markov-model.json differs from the lock`);
  if (sha256Hex(readFileSync(join(dir, "luau", "model.luau"))) !== lockRec.hashes.modelLuau) throw new Error(`${profile}: luau/model.luau differs from the lock`);
  return lockRec;
}

async function predict(profile, phase) {
  const dir = runDir(profile);
  if (!existsSync(join(dir, "model-lock.json"))) throw new Error(`${profile} has no model lock`);
  verifyLock(profile);
  const ledgerFile = join(dir, `predictions-${phase}.jsonl`);
  refuseExisting(ledgerFile);
  const { result, rows } = await runLuau("lab/cli/predict.luau", [profile, phase], { cwd: root });
  const forecasts = rows.filter((r) => !r.failure);
  const failures = rows.filter((r) => r.failure);
  const ids = new Set();
  for (const r of rows) {
    if (ids.has(r.id)) throw new Error(`duplicate forecast id ${r.id}`);
    ids.add(r.id);
  }
  const sha = writeJsonl(ledgerFile, forecasts);
  const fsha = writeJsonl(join(dir, `failures-${phase}.jsonl`), failures);
  const record = { runId: `${profile}-a1`, phase, forecasts: forecasts.length, failures: failures.length, sha256: sha, failuresSha256: fsha, canonicalSha256: canonicalSha256(forecasts), result, exportedAt: new Date().toISOString() };
  writeJson(join(dir, `ledger-${phase}.json`), record);
  console.log(JSON.stringify(record));
}

// Writes the experiment manifest. Once a release-ready manifest exists it is frozen: evaluation verifies the
// ledgers against it and never regenerates it.
function manifest() {
  const protocol = readJson(join(expDir, "protocol.json"));
  const profiles = protocol.profiles.included;
  const file = join(expDir, "experiment-manifest.json");
  if (existsSync(file) && readJson(file).releaseReady) throw new Error("a release-ready manifest is frozen");
  const out = { experimentId: EXP, protocol: protocol.sha256, included: profiles, profiles: {}, writtenAt: new Date().toISOString() };
  for (const p of profiles) {
    const dir = runDir(p);
    const lockRec = existsSync(join(dir, "model-lock.json")) ? verifyLock(p) : null;
    const ledger = existsSync(join(dir, "ledger-final.json")) ? readJson(join(dir, "ledger-final.json")) : null;
    out.profiles[p] = {
      locked: !!lockRec,
      modelSha256: lockRec?.hashes.model ?? null,
      modelLuauSha256: lockRec?.hashes.modelLuau ?? null,
      finalLedger: ledger ? { sha256: ledger.sha256, failuresSha256: ledger.failuresSha256, forecasts: ledger.forecasts, failures: ledger.failures } : null,
    };
  }
  out.releaseReady = profiles.every((p) => out.profiles[p].locked && out.profiles[p].finalLedger);
  writeJson(file, out);
  console.log(JSON.stringify(out));
}

function readJsonl(file) {
  return readFileSync(file, "utf8").split("\n").filter(Boolean).map((l) => JSON.parse(l));
}

function recordToLuau(r) {
  const keys = Object.keys(r).sort();
  return `{ ${keys.map((k) => `${k} = ${typeof r[k] === "string" ? JSON.stringify(r[k]) : typeof r[k] === "boolean" ? String(r[k]) : num(r[k])}`).join(", ")} }`;
}

// Independent Node recomputation of point metrics from the exported ledgers and outcomes.
function nodeMetrics(forecasts, outcomes) {
  const out = new Map();
  const byId = new Map(outcomes.map((o) => [o.forecastId, o]));
  for (const f of forecasts) {
    const o = byId.get(f.id);
    if (!o || !o.eligible) continue;
    const key = `${f.runId}:${f.modelId}|${f.symbol}`;
    const g = out.get(key) ?? { n: 0, se: 0, ae: 0, hit: 0, dirTotal: 0 };
    const e = f.prediction - o.actual;
    g.n++;
    g.se += e * e;
    g.ae += Math.abs(e);
    if (o.actual !== 0) {
      g.dirTotal++;
      if (f.prediction !== 0 && f.prediction > 0 === o.actual > 0) g.hit++;
    }
    out.set(key, g);
  }
  const res = {};
  for (const [k, g] of out) res[k] = { n: g.n, rmse: Math.sqrt(g.se / g.n), mae: g.ae / g.n, directionAccuracy: g.dirTotal ? g.hit / g.dirTotal : null };
  return res;
}

async function evaluate() {
  const profiles = ["O14", "R50", "H14"];
  const manFile = join(expDir, "experiment-manifest.json");
  if (!existsSync(manFile)) throw new Error("run `run-lab manifest` first: the release manifest must be frozen before evaluation");
  const man = readJson(manFile);
  if (!man.releaseReady) throw new Error("release gate closed: every profile must be locked with an exported final ledger");
  if (JSON.stringify(man.included) !== JSON.stringify(profiles)) throw new Error("manifest profiles differ from the evaluated set");
  const evalFile = join(expDir, "evaluation-final.json");
  refuseExisting(evalFile);
  const forecastsAll = [];
  for (const p of profiles) {
    const dir = runDir(p);
    const lockRec = verifyLock(p);
    const ledger = readJson(join(dir, "ledger-final.json"));
    const m = man.profiles[p];
    if (m.modelSha256 !== lockRec.hashes.model || m.finalLedger.sha256 !== ledger.sha256 || m.finalLedger.failuresSha256 !== ledger.failuresSha256) throw new Error(`${p}: ledger or lock differs from the frozen manifest`);
    const file = join(dir, "predictions-final.jsonl");
    const text = readFileSync(file);
    if (sha256Hex(text) !== ledger.sha256) throw new Error(`${p}: final ledger bytes changed since export`);
    const ftext = readFileSync(join(dir, "failures-final.jsonl"));
    if (sha256Hex(ftext) !== ledger.failuresSha256) throw new Error(`${p}: failures ledger bytes changed since export`);
    const forecasts = readJsonl(file);
    const failures = readJsonl(join(dir, "failures-final.jsonl"));
    for (const f of forecasts) {
      if (f.modelHash !== lockRec.hashes.model) throw new Error(`${p}: forecast ${f.id} carries model hash ${f.modelHash}, lock says ${lockRec.hashes.model}`);
    }
    forecastsAll.push(...forecasts);
    writeChunks(join(dir, "luau", "predictions-final"), forecasts, recordToLuau, { count: forecasts.length, sha256: ledger.sha256 });
    writeChunks(join(dir, "luau", "failures-final"), failures, recordToLuau, { count: failures.length, sha256: ledger.failuresSha256 });
  }
  const { result, rows } = await runLuau("lab/cli/evaluate.luau", ["final"], { cwd: root });
  const outSha = writeJsonl(join(expDir, "outcomes-final.jsonl"), rows);
  // independent recomputation and agreement check (1e-10 in log-return units)
  const node = nodeMetrics(forecastsAll, rows);
  const disagreements = [];
  const luauKeys = new Set();
  for (const p of profiles) {
    for (const m of result.profiles[p].metrics) {
      if (m.split !== "final" || !(m.n > 0)) continue;
      const k = `${m.runId}:${m.modelId}|${m.symbol}`;
      luauKeys.add(k);
      const n = node[k];
      if (!n) {
        disagreements.push({ k, f: "group", luau: m.n, node: null });
        continue;
      }
      for (const f of ["rmse", "mae", "directionAccuracy"]) {
        if (m[f] == null && n[f] == null) continue;
        if (Math.abs((m[f] ?? NaN) - (n[f] ?? NaN)) > 1e-10 || Number.isNaN(Math.abs((m[f] ?? NaN) - (n[f] ?? NaN)))) disagreements.push({ k, f, luau: m[f], node: n[f] });
      }
      if (m.n !== n.n) disagreements.push({ k, f: "n", luau: m.n, node: n.n });
    }
  }
  for (const k of Object.keys(node)) if (!luauKeys.has(k)) disagreements.push({ k, f: "group", luau: null, node: node[k].n });
  if (luauKeys.size === 0) disagreements.push({ k: "*", f: "no final metric groups compared" });
  const evaluation = { ...result, outcomesSha256: outSha, nodeRecomputation: { groups: Object.keys(node).length, compared: luauKeys.size, disagreements }, evaluatedAt: new Date().toISOString() };
  writeJson(evalFile, evaluation);
  console.log(JSON.stringify({ outcomes: rows.length, disagreements: disagreements.length, comparisons: result.comparisons.map((c) => ({ label: c.label, ok: c.ok, interval: c.interval })) }, null, 1));
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const [cmd, ...rest] = process.argv.slice(2);
  if (cmd === "evaluate") await evaluate();
  else if (cmd === "prepare") await prepare(rest[0]);
  else if (cmd === "streams") streams(rest[0], parseOpts(rest.slice(1)));
  else if (cmd === "assemble") assemble(rest[0], rest[1], rest[2].split(","));
  else if (cmd === "fit") await fit(rest[0]);
  else if (cmd === "lock") await lock(rest[0]);
  else if (cmd === "predict") await predict(rest[0], rest[1]);
  else if (cmd === "manifest") manifest();
  else {
    console.error("usage: run-lab.mjs prepare|streams|assemble ...");
    process.exit(2);
  }
}
