// Converts Studio state pages (runs/<runId>/state-cache/<stream>/page-NNNNNN.json, written by the bridge)
// into chunked Luau data modules the CLI can require:
//   runs/<runId>/luau/states_<stream>/index.luau     {count, keys, pageHashes, sha256, chunks}
//   runs/<runId>/luau/states_<stream>/ChunkNNN.luau  {{i, t, seg, off, {48 for keys[1]}, {48 for keys[2]}, ...}, ...}
// Validates contiguous indices from 1, consistent keys, 48 finite values per key, and records page hashes.
// Usage: node tools/states-to-luau.mjs <runId> <stream> [--expect <count>]
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHUNK = 1000;

export function loadStatePages(dir) {
  const names = readdirSync(dir).filter((n) => /^page-\d{6}\.json$/.test(n)).sort();
  if (names.length === 0) throw new Error(`no state pages in ${dir}`);
  const rows = [];
  const pageHashes = [];
  let keys = null;
  names.forEach((name, k) => {
    const bytes = readFileSync(join(dir, name));
    const page = JSON.parse(bytes.toString("utf8"));
    if (page.page !== k + 1) throw new Error(`${name}: page number ${page.page}, expected ${k + 1}`);
    if (keys === null) keys = page.keys;
    if (JSON.stringify(page.keys) !== JSON.stringify(keys)) throw new Error(`${name}: reservoir keys changed`);
    pageHashes.push(createHash("sha256").update(bytes).digest("hex"));
    for (const r of page.rows) {
      if (r.i !== rows.length + 1) throw new Error(`${name}: row index ${r.i}, expected ${rows.length + 1}`);
      for (const key of keys) {
        const s = r.s[key];
        if (!Array.isArray(s) || s.length !== 48 || !s.every(Number.isFinite)) throw new Error(`${name}: bad state for ${key} at ${r.i}`);
      }
      rows.push(r);
    }
  });
  return { rows, keys, pageHashes };
}

function num(x) {
  if (!Number.isFinite(x)) throw new Error(`non-finite ${x}`);
  return Object.is(x, -0) ? "-0" : String(x);
}

export function writeStateChunks(outDir, { rows, keys, pageHashes }) {
  mkdirSync(outDir, { recursive: true });
  const chunks = [];
  for (let c = 0; c * CHUNK < rows.length; c++) {
    const name = `Chunk${String(c + 1).padStart(3, "0")}`;
    const body = rows
      .slice(c * CHUNK, (c + 1) * CHUNK)
      .map((r) => `{${[r.i, r.t, r.seg, r.off].map(num).join(",")},${keys.map((k) => `{${r.s[k].map(num).join(",")}}`).join(",")}}`)
      .join(",\n");
    writeFileSync(join(outDir, `${name}.luau`), `return {\n${body}\n}\n`, "utf8");
    chunks.push(name);
  }
  const sha256 = createHash("sha256").update(pageHashes.join("\n")).digest("hex");
  const index =
    "-- GENERATED by tools/states-to-luau.mjs from bridge state pages. Do not edit.\n" +
    `return { count = ${rows.length}, keys = { ${keys.map((k) => JSON.stringify(k)).join(", ")} }, ` +
    `sha256 = "${sha256}", pageHashes = { ${pageHashes.map((h) => `"${h}"`).join(", ")} }, ` +
    `chunks = { ${chunks.map((c) => `"${c}"`).join(", ")} } }\n`;
  writeFileSync(join(outDir, "index.luau"), index, "utf8");
  return { count: rows.length, keys, sha256, chunks: chunks.length };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const [runId, stream] = process.argv.slice(2);
  const expectIdx = process.argv.indexOf("--expect");
  const dir = join(root, "runs", runId, "state-cache", stream);
  if (!existsSync(dir)) throw new Error(`missing ${dir}`);
  const data = loadStatePages(dir);
  if (expectIdx > 0 && data.rows.length !== Number(process.argv[expectIdx + 1])) {
    throw new Error(`expected ${process.argv[expectIdx + 1]} rows, found ${data.rows.length}`);
  }
  const res = writeStateChunks(join(root, "runs", runId, "luau", `states_${stream}`), data);
  console.log(JSON.stringify(res));
}
